//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSepetDetay
    {
        public int SepetDetayId { get; set; }
        public Nullable<int> KisiId { get; set; }
        public Nullable<int> SepetId { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<decimal> Adet { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<decimal> AraToplam { get; set; }
        public string KdvToplami { get; set; }
        public Nullable<double> KdvOrani { get; set; }
    }
}
