//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProfilShow
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string UserEmail { get; set; }
        public string Phone { get; set; }
        public int PersonId { get; set; }
    }
}
