//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrderPrice
    {
        public int OrderPriceId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderPiece { get; set; }
        public Nullable<double> OrderTex { get; set; }
        public Nullable<double> OrderlSub { get; set; }
        public Nullable<double> OrderTotalPrice { get; set; }
    }
}
