//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWUrunVeKategoriler
    {
        public Nullable<int> KategoriId { get; set; }
        public int UrunId { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> KdvOrani { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
    }
}
