//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayers
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeniAdresTablosu
    {
        public int ID { get; set; }
        public string SehirIlceMahalleAdi { get; set; }
        public Nullable<int> UstID { get; set; }
    }
}
